services:
  nodejs:
    container_name: node
    build: .
    ports: 
      - "3000:3000"
    environment:
      - MONGO_ADDR=172.16.8.3:27017
    depends_on:
      - mongodb
    networks:
      node_mongo:
        ipv4_address: "172.16.8.2"
    
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      node_mongo:
        ipv4_address: "172.16.8.3"
    volumes:
      - mongo_data:/data/db

networks:
  node_mongo:
    ipam:
      driver: default
      config:
        - subnet: "172.16.8.0/24"

volumes:
  mongo_data: 